import Head from 'next/head'

type HeadProps = {
    title: string
}

export const HtmlHead = ({ title }: HeadProps) => {
  return (
    <Head>
        <title>{title ? `Aglane - ${title}` :  'Aglane Website'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}
